### ISSUE TITLE
Error when Plex token starts with a hyphen

### ISSUE THREAD

**Issue by guytheys** [jyggen/intro-detection-info#1]
My X-Plex-Token starts with a hyphen (-FVxxxxx) and this causes the tool to throw this error when executing:
Error: unknown shorthand flag: 'F' in -FVxxxxx

**Comment by jyggen** [comment]
Hey! Sorry about the late reply, completely missed this issue.

You should be able to simply wrap the token in `"` or `'`, e.g. `./intro-detection-info <base-url> "-FVxxxxx"`.

**Comment by guytheys** [comment]
No problem!
Can confirm this works, thanks!
