### ISSUE TITLE
Save in Log File?

### ISSUE THREAD

**Issue by gelsas** [jyggen/intro-detection-info#3]
Hi is it possible to save the output in a logfile?

When using this script when I am connected via Putty to my Server then it generates the whole info but I can not scroll fully up anymore to see the info for all shows.

Would love to be able to just add something like this to the command: --logfile /location/folder/intro-detection-info.log

**Comment by gelsas** [comment]
I tried it like this:
./intro-detection-info http://DOMAIN:32400/ TOKEN > introinfo.log

But the result is like this and sadly not really readable:

+--------------------------------+--------+----------+--------------------------------+
|              SHOW         | SEASON | DETECTED |       COMMENT             |
+--------------------------------+--------+----------+--------------------------------+
| Show 1              |      1 | [0;33mPartial[0m | Episodes 1, 10, 11 and 13 do   |

**Comment by jyggen** [comment]
I've released a new version that allows you to run the application with `--colors=false`. There's also `--format=csv` to get a more machine-friendly output.
